spring.application.name=Ecommerce-Api

spring.datasource.url=jdbc:postgresql://localhost:5432/ecommerce-db
spring.datasource.username=postgres
spring.datasource.password=mani:2007
spring.datasource.driver-class-name=org.postgresql.Driver
